pipeline {
	agent any
		stages {
			stage('Clean stage') {
				steps {
					dir("MiscTopicsDemo") {
						bat 'C:\Program Files\apache-maven-3.8.4 mvn clean'
					}
				}
			}
			stage('Compile stage') {
				steps {
					dir("MiscTopicsDemo") {
						bat 'C:\Program Files\apache-maven-3.8.4 mvn compile'
					}
				}
			}
			stage('Install stage') {
				steps {
					dir("MiscTopicsDemo") {
						bat 'C:\Program Files\apache-maven-3.8.4 mvn install'
					}
				}
			}
		}
}
